config/routes.rb
Rails.application.routes.draw do


  resources :resorts, only: [:home, :index, :show] do
    # resources :bookings, only: [:create]
  end
  # resources :bookings, only: [:index, :show, :edit, :update]
  # resources :favorite_resorts, only: [:create, :destroy, :index]

  devise_for :users
  root to: 'pages#home'

  # get "favorites/", to: "favorite_resorts#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :resorts
  validates :name, presence: true, uniqueness: true
  validates :airport_code, presence: true, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :resort
end

app/models/feature.rb
class Feature < ApplicationRecord
  has_many :feature_resorts, dependent: :destroy
  has_many :resorts, through: :feature_resorts
  validates :name, presence: true, uniqueness: true
end

app/models/feature_resort.rb
class FeatureResort < ApplicationRecord
  belongs_to :feature
  belongs_to :resort
  validates :feature_id, presence: true
  validates :resort_id, presence: true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :resort
end

app/models/resort.rb
class Resort < ApplicationRecord
  belongs_to :user
  belongs_to :airport
  has_many :feature_resorts
  has_many :features, through: :feature_resorts


  # geocoded_by :address
  # after_validation :geocode, if: :will_save_change_to_address?

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  # validates :name, presence: true
  # validates :continent, presence: true
  # validates :country, presence: true
  # validates :address, presence: true
  # validates :photo, presence: true
  # validates :description, presence: true
  # validates :user_id, presence: true
  # validates :airport_id, presence: true
  # validates :website, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :resorts
  validates :password, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/favourites_controller.rb
class FavouriteResortsController < ApplicationController
  before_action :set_resort, only: [:create, :destroy]
  skip_after_action :verify_authorized

  def index

    @resorts = current_user.favourite_resorts

    @markers = @resorts.map do |resort|
    {
      lat: resort.latitude,
      lng: resort.longitude
    }
    end
  end


  def create
    current_user.favourite_resorts << @resort
    redirect_to request.referer
    # if current_page?(resorts_path)
    #   redirect_to resorts_path
    # else
    #   redirect_to resorts_path(@resort)
    # end
  end

  def destroy
    Favourite.where(favourited_id: @resort.id, user_id: current_user.id).first.destroy
    redirect_to request.referer
    # if current_user
    #   redirect_to resorts_path
    # end
  end

    private

    def set_resort
      @resort = Resort.find(params[:resort_id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/resorts_controller.rb
class ResortsController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_resort, only: [:show, :edit, :update, :destroy]

  def index
    @resorts = Resort.where.not(latitude: nil, longitude: nil)


    if params[:location].present?
      sql_query = "country ILIKE :location OR continent ILIKE :location"
      @resorts = @resorts.where(sql_query, location: "%#{params[:location]}%")
    end

    if params[:feature].present?
       sql_query = "features.name ILIKE :feature"
      @resorts = @resorts.joins(:features).where(sql_query, feature: "%#{params[:feature]}%")
    end

      @markers = @resorts.map do |resort|
    {
      lat: resort.latitude,
      lng: resort.longitude
    }
    end
  end

  # def show
  #   @booking = Booking.new
  # end

  # def favourite
  #   type = params[:type]
  #   if type == "favourite"
  #     current_user.favourites << @resort
  #     redirect_to :back, notice: "You favourited #{@resort.name}"

  #   elsif type == "unfavourite"
  #     current_user.favourites.delete(@resort)
  #     redirect_to :back, notice: "Unfavourited #{@resort.name}"

  #   else
  #     # Type missing, nothing happens
  #     redirect_to :back, notice: 'Nothing happened.'
  #   end
  # end


  private

  def set_resort
    @resort = Resort.find(params[:id])
    authorize @resort
  end

  def resort_params
    params.require(:resort).permit(:name, :continent, :country, :address, :price, :description )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>teepee | home</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div style="min-height: calc(100vh - 170px);">
      <%= yield %>
    </div>
     <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
 <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag "maps" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="flexbox">
<!-- Carousel
================================================== -->
<div class="carousel slide" id ="slider" data-ride="carousel1">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li class="active" data-slide-to="0" data-target="#slider"></li>
    <li data-slide-to="1" data-target="#slider"></li>
    <li data-slide-to="2" data-target="#slider"></li>
  </ol>

  <div class="carousel-inner">
    <div class="item active" id="item1" style="background-image: linear-gradient(rgba(222, 191, 153, 0.19), rgba(39, 13, 13, 0.38) ), url('https://www.myvacationpages.com/data/post-images/2013/12/the-beloved-resort.jpg')">
    </div>

    <div class="item" style="background-image: linear-gradient(rgba(222, 191, 153, 0.19), rgba(39, 13, 13, 0.38) ), url('https://www.mykonosgrand.gr/wp-content/uploads/2014/06/homepage-slide2-01-v2.jpg')">
    </div>

    <div class="item" style="background-image: linear-gradient(rgba(222, 191, 153, 0.19), rgba(39, 13, 13, 0.38) ), url('https://cdn.downunderendeavours.com/wp-content/uploads/2014/08/D112-hero2000x837-Namale_Villas_CivaDuavata_InfinityPool.jpg')">
  </div>
<div class="absolute-container">
  <h1 class="home-h1">EXPLORE AND ESCAPE</h1>
  <h3 class="home-h3">Plan your luxury holiday with the activities you love</h3>

  <div class="search-form">
          <%= form_tag(resorts_path, method: :get) do %>
          <%= text_field_tag :location, nil, placeholder: 'Where?' %>
          <%= text_field_tag :feature, nil, placeholder: 'What activity?' %>
          <%= submit_tag 'Search', name: nil, class:"submit" %>
          <% end %>
  </div>
</div>

  <!-- Controls -->
  <a class="left carousel-control" href="#slider" data-slide="prev" role="button"><span class=" icon-prev"></span></a>


 <a class="right carousel-control" href="#slider" data-slide="next" role="button"><span class=" icon-next"></span></a>

</div>
</div>

app/views/resorts/index.html.erb
<h3>Resorts</h3>
<!-- <p>Find me in app/views/resorts/index.html.erb</p> -->
<div class="line">
</div>

<div class="main-container">
 <div class="card-container">
   <div class="row deleting-padding">

     <% @resorts.uniq.each do |resort| %>
       <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4">

       <%= link_to resort_path(resort), target: :_blank do %>
       <div class="card-resort" class="resort" style="background-image: url(<%= image_path resort.photo %>);">

       </div>
       <% end %>
  <!--      <div>
         <% if current_user %>

           <% if current_user.likes?(resort) %>

              <%= link_to favorite_resort_path(resort, resort_id: resort), method: :delete do %>
              <%= icon("fas", "heart") %>
             <% end %>

           <% else %>

            <%= link_to favorite_resorts_path(resort_id: resort), method: :post do %>
              <%= icon("far", "heart") %>
            <% end %>

          <% end %>
          <% end  %>
         </div> -->

       <div class=" text ">
         <div input type="text" class="location"><%= "#{resort.country}, #{resort.continent} " %> </div>
         <div input type="text" class="name"> <%= link_to resort.name, resort_path(resort) %></div>
       </div>
     </div>
     <% end %>
   </div>
 </div>

 <div id="map" data-markers="<%= @markers.to_json %>"></div>
</div>

app/views/resorts/show.html.erb
<div class="container-top-show-resort">
  <div class="row">
    <div class="hidden-sm-down col-md-6 col-lg-4">
      <div class="resort-name">
        <div class="resort-address">
          <p> Resort in <%= @resort.address %></p>
        </div>
        <div class="stars">
          <i class="fas fa-star"></i>
          <i class="fas fa-star"></i>
          <i class="fas fa-star"></i>
          <i class="fas fa-star"></i>
          <i class="fas fa-star"></i>
        </div>
        <h3> <%=  @resort.name %> </h3>
      </div>
    </div>
    <div class="col-sm-12 col-md-6 col-lg-8">

      <div class="resort-picture" style=" background-image: url(<%= image_path @resort.image %>);">
        <% if current_user %>
          <% if current_user.likes?(@resort) %>
            <%= link_to favorite_resort_path(@resort, resort_id: @resort), method: :delete do %>
              <%= icon("fas", "heart") %>
            <% end %>
          <% else %>
            <%= link_to favorite_resorts_path(resort_id: @resort), method: :post do %>
              <%= icon("far", "heart") %>
            <% end %>
          <% end %>
          <% end  %>
      <!--   <i class="far fa-heart"></i> -->

     <!--  <div class="resort-picture" style=" background-image: url(<%= image_path @resort.image %>);">
        <i class="far fa-heart"></i>
        <i class="far fa-share-square"></i>
 -->
      </div>
    </div>
  </div>
</div>


<div class="resort-description">
  <p><%=  @resort.description %> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
  cillum dolore eu fugiat nulla pariatur.</p>
</div>

<div class="row-show-resort">
  <div class="col-sm-12 col-md-12 col-lg-12 visit-this-resort">
    <h3 id="visit">Visit this resort</h3>
    <div class="row-show-resort">
      <div class="visit-resort">
        <div class="col-sm-6 col-md-3 col-lg-3">
          <img src="http://www.furnishburnish.com/wp-content/uploads/2012/07/making-cozy-home5.jpg">
          <p>Rooms</p>
        </div>
        <div class="col-sm-6 col-md-3 col-lg-3">
          <img src="https://www.hurawalhi.com/wp-content/uploads/2016/09/Hurawalhi_Aquarium_Sunrise.jpg">
          <p>Facilities</p>
        </div>
        <div class="col-sm-6 col-md-3 col-lg-3">
          <img src="https://s3.amazonaws.com/busites_www/mvkeywestresort/banner_pool_green_towels_1506033934.jpg">
          <p>Pool</p>
        </div>
        <div class="col-sm-6 col-md-3 col-lg-3">
          <img src="https://www.omnihotels.com/-/media/images/hotels/mtwash/restaurants/mtwash-omni-mount-washington-resort-cave-bar-1.jpg">
          <p>Bar</p>
        </div>
      </div>
      </div>
    </div>
  </div>


<div class="show-banner" style=" background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://www.popsci.com/sites/popsci.com/files/images/2017/06/beach-wave.jpg');">
  <div class="text-banner-show-resort">
    <h4 class="title-show-resort">WELCOME HOME</h4>
    <p class="description-show-resort">Visit <%= @resort.country %> like you've never seen</p>
  </div>
</div>


<footer class="footer-show-resort">
  <div class="relative-footer">
    <p class="address-footer"> Resort in <%= @resort.address %></p>
    <div class="stars-footer">
      <i class="fas fa-star"></i>
      <i class="fas fa-star"></i>
      <i class="fas fa-star"></i>
      <i class="fas fa-star"></i>
      <i class="fas fa-star"></i>
    </div>
  </div>
  <div class="footer-form">
<!--     <%= form_for([@resort, @booking], layout: :inline) do |f| %>
      Start date: <%= f.date_field :start_date, as: :date, min: Date.today, label: "Start date" %>
      Duration: <%= f.number_field :duration, min: 1, label: "Duration" %>
      <span class="price"> <%= @resort.price %>€ </span>
      <span class="per-nigth">/nigth</span>
    <%= f.button submit: 'Bfewfwe' %> -->
    <% end %>
  </div>
</footer>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="line">
</div>
<div class="footer">
  <div class = "footer-copyright">
    Keep exploring. Follow us on social here...
  </div>
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

    <!-- Links when logged in -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="https://res.cloudinary.com/wagon/image/upload/c_fill,g_face,h_200,w_200/r629al5meq01gxyad2zz.jpg" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "My bookings", bookings_path %></li>
          <li><%= link_to "My favorites", favorite_resorts_path %></li>
          <li><%= link_to destroy_user_session_path, method: :delete do %>
              <%= t(".sign_out", default: "Log out") %>
              <% end %></li>
        </ul>
      </div>
    </div>

    <% else %>
  <!-- Login link (when logged out) -->
  <div class="home-signup">
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "btn btn-default" %>
  </div>
  <div>
    <%= link_to t(".sign_up", default: "Sign Up"), new_user_registration_path, class: "btn btn-warning" %>
      <% end %>
  </div>
  </div>
</div>